using System;
using System.Collections.Generic;

namespace data_doc_api.Models
{
    /// <summary>
    /// Represents a configured relationship in the database. The relationship can be manually entered, or be automatically scanned from source database.
    /// </summary>
    public class RelationshipInfo
    {
        /// <summary>
        /// Unique key.
        /// </summary>
        public int? RelationshipId { get; set; }

        /// <summary>
        /// The project id
        /// </summary>
        public int ProjectId { get; set; }

        /// <summary>
        /// The relationship / FK name
        /// </summary>
        public string RelationshipName { get; set; }

        /// <summary>
        /// The parent entity name
        /// </summary>
        public string ParentEntityName { get; set; }

        /// <summary>
        /// The referenced entity name
        /// </summary>
        public string ReferencedEntityName { get; set; }

        /// <summary>
        /// The parent attribute name(s)
        /// </summary>
        public List<string> ParentAttributeNames { get; set; }

        /// <summary>
        /// The referenced attribute name(s)
        /// </summary>
        public List<string> ReferencedAttributeNames { get; set; }

        /// <summary>
        /// Set to true for relationships that are automatically generated by the scanner.
        /// </summary>
        public bool IsScanned { get; set; }
    }
}